#!/usr/bin/env python3

import os
import sys
import nltk

from nltk.tokenize import TweetTokenizer
from analyzer import Analyzer
from helpers import get_user_timeline
from termcolor import colored

def main():

    # ensure proper usage
    if len(sys.argv) != 2:
        sys.exit("Usage: ./tweets @screen_name")
        
    # obtain tweets from screen_name (stripping @ if included so it works with get_user_timeline)
    list_tweets = get_user_timeline(sys.argv[1].lstrip('@'), 50)

    # error if unable to retrieve tweets (either invalid screen name or no tweets present)
    if list_tweets == None:
        sys.exit("Unable to retrieve tweets.")
        
    # absolute paths to lists
    positives = os.path.join(sys.path[0], "positive-words.txt")
    negatives = os.path.join(sys.path[0], "negative-words.txt")

    # instantiate analyzer
    analyzer = Analyzer(positives, negatives)
        
    # for each tweet, analyze each word and give a total score using analyzer.py
    for i in range(len(list_tweets)):
        score = analyzer.analyze(list_tweets[i])
        if score > 0.0:
            print(colored(" 1 " + list_tweets[i], "green"))
        elif score < 0.0:
            print(colored("-1 " + list_tweets[i], "red"))
        else:
            print(colored(" 0 " + list_tweets[i], "yellow"))

if __name__ == "__main__":
    main()
